### PR TITLE
support empty case

### PR DESCRIPTION
**Pull request by Shuraken007**

### CODE REVIEW

**Comment by Shuraken007** [comment]
The only problem, that I couldn't solve looks next way:
let we have text ```one two```
case cursor is on the edge of the world, e.g. ```one |two``` or ```one two|``` 
then selection appeared after creating quotes, selection contains quote at that edge, e.g.
```one |"|two``` or ```one "two|"|```

**Comment by jeremychone** [comment]
@Shuraken007 Question: But then, once empty, it cannot cycle back, right?

**Comment by Shuraken007** [comment]
@jeremychone released cycle back by nearest word, .e.g. `one 'tw|o three'` -> `one tw|o three` -> `one "tw|o" three` 
It's enough for my cases (case I need 2+ words - I select them)
I think - there are ways to make behaviour smarter. Remember last transformations(by multicursore) as example / reset them over some time

**Comment by jeremychone** [comment]
Hum, I am not sure this should be merged. Seems to be very specific. 

Also, I think important the command is stateless.

**Comment by jeremychone** [comment]
I am still debating myself back and forth on this one. First, big thanks on the PR, and second, since this is an optin, then, the user need to be aware of the consequence, so perhaps it is ok.

**Comment by jeremychone** [comment]
After review of the code, I cannot really merge this as it change the default sequence of characters. This will be a breaking change.

**Pull request closed without merging**
